# Generated by Django 5.1.7 on 2025-03-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
